#!/bin/bash
# ═══════════════════════════════════════════════════════
# Rook — Deploy alongside Jarvis on VPS
# Run this ON the VPS: bash deploy_rook.sh
# ═══════════════════════════════════════════════════════

set -e

ROOK_DIR="/opt/rook"
JARVIS_ENV="/opt/jarvis/.env"
ROOK_ENV="$ROOK_DIR/.env"

echo "♜ Rook — Deployment Script"
echo "════════════════════════════"

# ── Step 1: Clone repo ──
echo ""
echo "[1/6] Cloning Rook repository..."
if [ -d "$ROOK_DIR" ]; then
    echo "  → $ROOK_DIR exists, pulling latest..."
    cd "$ROOK_DIR" && git pull origin main
else
    git clone https://github.com/barman1985/Rook.git "$ROOK_DIR"
    cd "$ROOK_DIR"
fi

# ── Step 2: Virtual environment ──
echo ""
echo "[2/6] Setting up Python venv..."
if [ ! -d "$ROOK_DIR/venv" ]; then
    python3 -m venv "$ROOK_DIR/venv"
fi
source "$ROOK_DIR/venv/bin/activate"

# ── Step 3: Install dependencies ──
echo ""
echo "[3/6] Installing dependencies..."
pip install -q -r requirements.txt 2>&1 | tail -3

# ── Step 4: Extract keys from Jarvis ──
echo ""
echo "[4/6] Extracting configuration from Jarvis..."

get_jarvis_key() {
    local key="$1"
    grep "^${key}=" "$JARVIS_ENV" 2>/dev/null | head -1 | cut -d'=' -f2-
}

ANTHROPIC_KEY=$(get_jarvis_key "ANTHROPIC_API_KEY")
TG_TOKEN=$(get_jarvis_key "TELEGRAM_BOT_TOKEN")
TG_CHAT=$(get_jarvis_key "TELEGRAM_CHAT_ID")
SPOTIFY_ID=$(get_jarvis_key "SPOTIFY_CLIENT_ID")
SPOTIFY_SECRET=$(get_jarvis_key "SPOTIFY_CLIENT_SECRET")
SPOTIFY_REFRESH=$(get_jarvis_key "SPOTIFY_REFRESH_TOKEN")
OWM_KEY=$(get_jarvis_key "OWM_API_KEY")

# Check required keys
if [ -z "$ANTHROPIC_KEY" ]; then
    echo "  ⚠ ANTHROPIC_API_KEY not found in Jarvis .env"
    echo "  Enter it manually:"
    read -p "  ANTHROPIC_API_KEY: " ANTHROPIC_KEY
fi

if [ -z "$TG_TOKEN" ]; then
    echo "  ⚠ TELEGRAM_BOT_TOKEN not found in Jarvis .env"
    echo ""
    echo "  IMPORTANT: Rook needs its OWN Telegram bot!"
    echo "  → Go to @BotFather on Telegram"
    echo "  → /newbot → name it 'Rook' or 'Rook AI'"
    echo ""
    read -p "  New TELEGRAM_BOT_TOKEN for Rook: " TG_TOKEN
else
    echo ""
    echo "  ⚠ IMPORTANT: Rook should use a SEPARATE Telegram bot!"
    echo "  Jarvis bot token found, but sharing it will cause conflicts."
    echo "  → Go to @BotFather → /newbot → name it 'Rook'"
    echo ""
    read -p "  Use Jarvis token for testing (j) or enter new (n)? [j/n]: " TG_CHOICE
    if [ "$TG_CHOICE" = "n" ]; then
        read -p "  New TELEGRAM_BOT_TOKEN for Rook: " TG_TOKEN
    fi
fi

if [ -z "$TG_CHAT" ]; then
    echo "  ⚠ TELEGRAM_CHAT_ID not found"
    read -p "  TELEGRAM_CHAT_ID: " TG_CHAT
fi

echo "  ✓ Keys extracted"

# ── Step 5: Write .env ──
echo ""
echo "[5/6] Writing Rook .env..."

cat > "$ROOK_ENV" << ENVEOF
# Rook configuration — generated by deploy script
# $(date)

# Required
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
TELEGRAM_BOT_TOKEN=${TG_TOKEN}
TELEGRAM_CHAT_ID=${TG_CHAT}

# Google (reuse Jarvis credentials)
GOOGLE_CREDENTIALS_PATH=/opt/jarvis/credentials.json

# Spotify
SPOTIFY_CLIENT_ID=${SPOTIFY_ID}
SPOTIFY_CLIENT_SECRET=${SPOTIFY_SECRET}

# Models
MAIN_MODEL=claude-sonnet-4-20250514
ROUTER_MODEL=claude-haiku-4-5-20251001

# System
TIMEZONE=Europe/Prague
LOG_LEVEL=INFO
DB_PATH=/opt/rook/rook.db
ENVEOF

echo "  ✓ .env written"

# ── Step 5b: Symlink Google token ──
if [ -f "/opt/jarvis/token.json" ]; then
    ln -sf /opt/jarvis/token.json "$ROOK_DIR/token.json" 2>/dev/null || cp /opt/jarvis/token.json "$ROOK_DIR/token.json"
    echo "  ✓ Google token.json linked"
fi

# ── Step 6: Test run ──
echo ""
echo "[6/6] Testing Rook..."
cd "$ROOK_DIR"
python3 -c "
import sys
sys.path.insert(0, '.')
from rook.core.config import cfg
errors = cfg.validate()
if errors:
    print(f'  ✗ Missing: {errors}')
    sys.exit(1)
print(f'  ✓ Config valid')
print(f'  ✓ Features: {cfg.summary().splitlines()[1]}')

from rook.core.db import init_db
init_db()
print(f'  ✓ Database initialized')

from rook.skills.loader import load_skills, get_all_tools
skills = load_skills()
tools = get_all_tools()
print(f'  ✓ Skills: {len(skills)} loaded, {len(tools)} tools')
print(f'    {chr(10).join(f\"    {n} ({len(s.get_tools())} tools)\" for n, s in skills.items())}')
"

echo ""
echo "════════════════════════════"
echo "✓ Rook deployed to $ROOK_DIR"
echo ""
echo "To start:"
echo "  cd $ROOK_DIR && source venv/bin/activate && python -m rook.main"
echo ""
echo "To run as service (systemd):"
echo "  sudo cp rook.service /etc/systemd/system/"
echo "  sudo systemctl enable --now rook"
echo ""
echo "♜ Rook — your strategic advantage"
